#!/bin/bash
# kill running m4bs instance (when removing)
[ "$1" == "remove" ] && killall m4bs-cli 2> /dev/null || true
[ "$1" == "remove" ] && killall m4bs-info 2> /dev/null || true
[ "$1" == "remove" ] && killall m4bs-log 2> /dev/null || true
[ "$1" == "remove" ] && killall m4bs-mount 2> /dev/null || true
[ "$1" == "remove" ] && killall m4bs-start 2> /dev/null || true
[ "$1" == "remove" ] && killall m4bs-stop 2> /dev/null || true
[ "$1" == "remove" ] && killall m4bs-status 2> /dev/null || true
[ "$1" == "remove" ] && killall m4bs-update 2> /dev/null || true
