#! /bin/bash

# This program is just an example of how to make a whiptail menu and some basic commands.
# Copyright (C) 2021  Destroyer  dcf.maker@gmail.com

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3
# of the License.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

function echo_red {
	m4bs_echo "31m" "$1"
}

function echo_no_colour {
	echo "$1"
}

function echo_yellow {
	m4bs_echo "33m" "$1"
}

function echo_green {
	m4bs_echo "32m" "$1"
}

function _echo_cyan {
	m4bs_echo "36m" "$1"
}

function m4bs_echo {
		echo -e "\033[1;$1$2\033[0m"
}

get_user() {
	if [ "$EUID" == 0 ]; then
		echo "Por favor no ejecute con usuario root"
		exit 1
	fi
}

do_log() {
  logger -p local0.notice -t [${0##*/}]:[$$] $1
}

function get_valid_ip(){
  # Set up local variables
  local ip=$1
  local IFS=.; local -a a=($ip)
  # Start with a regex format test
  [[ $ip =~ ^[0-9]+(\.[0-9]+){3}$ ]] || return 1
  # Test values of quads
  local quad
  for quad in {0..3}; do
    [[ "${a[$quad]}" -gt 255 ]] && return 1
  done
  return 0
}